### ISSUE TITLE
Course search fails to match on course number alone

### ISSUE THREAD

**Issue by JacksGo** [osu-capstone-cs72/cs-applied-plan-portal#26]
### Reproduction steps
 - Open the Create Plan page.
 - Enter "2" in the search box.
 - Click Search.

### Expected results
CS261, CS271, and CS290 should be found and displayed.

### Actual results
No courses are found.

### Recommendation
The search functionality should partial match on the course code's number as well as its prefix.

**Comment by silverware13** [comment]
Fixed by allowing fuzzier search results
