### ISSUE TITLE
Should we keep TEX files?

### ISSUE THREAD

**Issue by philectron** [osu-capstone-cs72/cs-applied-plan-portal#3]
In the past, I tried to keep TEX files as well as the PDF so I could have the source of the document. This created an issue. Since we write a lot in the TEX file, GitHub automatically picks up the language and makes LaTeX the dominant language in the repo, which we don't want.

I have a way to force GitHub to ignore LaTeX files in the language stats, though, by using `PATH/TO/FILE linguist-documentation` (see [here](https://github.com/github/linguist)) in `.gitattributes`.

We have two options:

1. Not keeping TEX files at all, only the PDFs
2. Keeping TEX files in source control, but ignoring it in language stats

Let me know what you think!

**Comment by silverware13** [comment]
I am leaning towards not keeping the TEX files as they should be historical documents. If for some reason once we finish our project another team picks it up, I imagine they would be required to write their own new documentation anyways.

**Comment by philectron** [comment]
@silverware13 You got a point. Also, I downloaded the Overleaf projects last night and tried to compile them locally. There were a lot of dependencies needed to even compile the document. So, I think just the PDFs are enough. I'm closing this one.
