### ISSUE TITLE
The first course selected when creating a plan never gives an error

### ISSUE THREAD

**Issue by silverware13** [osu-capstone-cs72/cs-applied-plan-portal#39]
The first course selected on the create plan page always will be accepted and will not give an error.

**Comment by philectron** [comment]
Repro steps, expected and actual results?

**Comment by silverware13** [comment]
Steps to reproduce:
From home page go to create plan page.
Search/filter CS courses.
Press the "+ Add to plan" button on any  course that should give an error (ex: CS261).
Notice how no error appears, notice how it still gets added to the left panel.
Try to add another plan with that should cause an error (ex: CS290).
Notice that it gives an error correctly and is not added to the left side of the screen.

**Comment by philectron** [comment]
This has been fixed, yes? If so, can somebody make a PR?

**Comment by clairecahill** [comment]
Yes this issue is fixed but there is a question I have about the expected behavior of the filter bar. I was hoping to show you all at the meeting tomorrow before submitting the PR.

**Comment by silverware13** [comment]
Sounds good, we can hold off on creating the PR until after our meeting.
