### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by philectron** [osu-capstone-cs72/cs-applied-plan-portal#46]
Well, it needs to be done, team. We should have written the tests first. Now, they are coming to haunt all of us.

Since we're not actively using [Trello](https://trello.com/c/sxtWmIm0/56-find-unit-testing-framework) (ahem), I'm putting this big task here as an Issue. As we previously discussed, here are a few interesting testing frameworks:

- [Jest](https://jestjs.io)
- [Storybook](https://storybook.js.org)

This task can be pushed to Spring if needed.

**Comment by silverware13** [comment]
Fixed by bf3a51f1.
