### ISSUE TITLE
Replace User ID with Total Credits in metadata bar

### ISSUE THREAD

**Issue by JacksGo** [osu-capstone-cs72/cs-applied-plan-portal#53]
A fairly straightforward proposal here. I think that having "Total Credits" in the metadata bar would be a better use of a space than User ID, which, on a practical level, has no significance to students or advisors. The current placement of the credit count, as an addition to the credit count column header, isn't prominent and doesn't allow an advisor to scan the plan quickly or effectively.

**Comment by silverware13** [comment]
I think one thing we need to ask at the meeting in general is if the advisors would find any value in having a user ID value. If they don't feel a need for it then I say we remove it visually from the front-end on all pages. In that case it would just remain on the back-end for us to reference or as a query param.

**Comment by JacksGo** [comment]
I doubt that it has any significance to them in their systems. After all, receptionists in EECS always take our ID cards and use the number from them, which is entirely disconnected from the ID we have access to through the API. But yeah, it couldn't hurt to ask.
