### ISSUE TITLE
Table headers have insufficient padding

### ISSUE THREAD

**Issue by JacksGo** [osu-capstone-cs72/cs-applied-plan-portal#58]
Table headers are much narrower than the data fields in the tbody. I believe this is a holdover from the removal of the base styling.

**Comment by philectron** [comment]
@JacksGo Do you think this is noticeable? If it's a quick fix, then feel free to go for it.

**Comment by JacksGo** [comment]
I don't see where this was occurring. It's possible I've missed something somewhere, but in any event, the next team should refactor the project to use a library of components, so this is largely a non-issue.
