### ISSUE TITLE
Improve security

### ISSUE THREAD

**Issue by philectron** [osu-capstone-cs72/cs-applied-plan-portal#65]
- [x] Resolve package vulnerability
- [x] Keep login credentials on cookies
  - [x]  Consider Rob's suggestion to get the entire application to run on a single port
- [x] Find ways to avoid xss attacks

**Comment by philectron** [comment]
Fixed most package vulnerabilities on [`security`](https://github.com/osu-capstone-cs72/cs-applied-plan-portal/commit/76e6fad7b4c2fe758d286e0a8407f8d9a759b9b0). Root and `client/` should be clear except 300 low ones in `client/` which caused by `minimist` which is a nested dependency of `react-scripts`.

**Comment by silverware13** [comment]
Pull request 'Security #70' stores login credentials using cookies, sets up a proxy for the React and API server, and uses multiple methods to reduce the potential danger of xss attacks.
