### ISSUE TITLE
Course results can overfill create plan page and make it impossible to see errors at the top of the screen

### ISSUE THREAD

**Issue by silverware13** [osu-capstone-cs72/cs-applied-plan-portal#74]
On the create plan page if a user searches for a broad enough topic they can expand the screen vertically to require scrolling to see more course results.

This can make it impossible to see the error messages that appear at the top of the page, as well as make it impossible to see the plan that the user is currently working on.

One possible solution is having the plan creation and the course search in two separate containers.
Each can be scrolled independently.

**Comment by JacksGo** [comment]
I've tried to remedy this in the past but was a bit penned in by the way the page's layout was implemented and spread across components. This is my first priority as we close in on the code review.

**Comment by silverware13** [comment]
Fixed by d6762c4
